name: deploy

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            cd /var/www/moonshinedeploy.ru
            php artisan down
            git pull
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            npm run production
            php artisan optimize:clear
            php artisan optimize
            php artisan queue:restart
            php artisan up
